[2024-11-20T04:48:50.415+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-11-20T04:46:39.560816+00:00 [queued]>
[2024-11-20T04:48:50.425+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-11-20T04:46:39.560816+00:00 [queued]>
[2024-11-20T04:48:50.426+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-20T04:48:50.441+0000] {taskinstance.py:2214} INFO - Executing <Task(DbtRunLocalOperator): publish.customer_metrics_run> on 2024-11-20 04:46:39.560816+00:00
[2024-11-20T04:48:50.445+0000] {standard_task_runner.py:60} INFO - Started process 18684 to run task
[2024-11-20T04:48:50.448+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'publish.customer_metrics_run', 'manual__2024-11-20T04:46:39.560816+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmpmr_zqnd8']
[2024-11-20T04:48:50.450+0000] {standard_task_runner.py:88} INFO - Job 156: Subtask publish.customer_metrics_run
[2024-11-20T04:48:50.498+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-11-20T04:46:39.560816+00:00 [running]> on host 4cf1ca1acf00
[2024-11-20T04:48:50.582+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='publish.customer_metrics_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T04:46:39.560816+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T04:46:39.560816+00:00'
[2024-11-20T04:48:50.583+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmp9uwevqsm from /opt/airflow/include/dbt/fraud
[2024-11-20T04:48:50.587+0000] {config.py:253} INFO - Using user-supplied profiles.yml at /opt/airflow/include/dbt/fraud/profiles.yml
[2024-11-20T04:48:50.587+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
From /tmp/tmp9uwevqsm
[2024-11-20T04:48:50.588+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])
[2024-11-20T04:48:50.589+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-11-20T04:48:50.589+0000] {subprocess.py:73} INFO - Running command: ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
[2024-11-20T04:48:50.600+0000] {subprocess.py:84} INFO - Command output:
[2024-11-20T04:48:52.447+0000] {subprocess.py:94} INFO - [0m04:48:52  Running with dbt=1.8.7
[2024-11-20T04:48:53.588+0000] {subprocess.py:94} INFO - [0m04:48:53  Registered adapter: snowflake=1.8.4
[2024-11-20T04:48:53.616+0000] {subprocess.py:94} INFO - [0m04:48:53  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-11-20T04:48:55.392+0000] {subprocess.py:94} INFO - [0m04:48:55  Found 3 models, 454 macros
[2024-11-20T04:48:55.394+0000] {subprocess.py:94} INFO - [0m04:48:55
[2024-11-20T04:49:01.210+0000] {subprocess.py:94} INFO - [0m04:49:01  Concurrency: 1 threads (target='dev')
[2024-11-20T04:49:01.211+0000] {subprocess.py:94} INFO - [0m04:49:01
[2024-11-20T04:49:01.217+0000] {subprocess.py:94} INFO - [0m04:49:01  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]
[2024-11-20T04:49:02.949+0000] {subprocess.py:94} INFO - [0m04:49:02  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [[31mERROR[0m in 1.73s]
[2024-11-20T04:49:02.952+0000] {subprocess.py:94} INFO - [0m04:49:02
[2024-11-20T04:49:02.953+0000] {subprocess.py:94} INFO - [0m04:49:02  Finished running 1 table model in 0 hours 0 minutes and 7.56 seconds (7.56s).
[2024-11-20T04:49:02.986+0000] {subprocess.py:94} INFO - [0m04:49:02
[2024-11-20T04:49:02.987+0000] {subprocess.py:94} INFO - [0m04:49:02  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-20T04:49:02.987+0000] {subprocess.py:94} INFO - [0m04:49:02
[2024-11-20T04:49:02.988+0000] {subprocess.py:94} INFO - [0m04:49:02    Database Error in model customer_metrics (models/customer_metrics.sql)
[2024-11-20T04:49:02.988+0000] {subprocess.py:94} INFO -   001003 (42000): SQL compilation error:
[2024-11-20T04:49:02.989+0000] {subprocess.py:94} INFO -   syntax error line 22 at position 24 unexpected ';'.
[2024-11-20T04:49:02.989+0000] {subprocess.py:94} INFO -   compiled code at target/run/fraud/models/customer_metrics.sql
[2024-11-20T04:49:02.989+0000] {subprocess.py:94} INFO - [0m04:49:02
[2024-11-20T04:49:02.990+0000] {subprocess.py:94} INFO - [0m04:49:02  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-11-20T04:49:04.215+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2024-11-20T04:49:04.231+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-11-20T04:49:04.232+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-11-20T04:49:04.241+0000] {local.py:252} INFO - Inlets: []
[2024-11-20T04:49:04.241+0000] {local.py:253} INFO - Outlets: []
[2024-11-20T04:49:04.242+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-11-20T04:49:04.265+0000] {dag.py:3834} INFO - Setting next_dagrun for customer_metrics to 2024-11-20 00:00:00+00:00, run_after=2024-11-21 00:00:00+00:00
[2024-11-20T04:49:04.291+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 257, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 136, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m04:48:52  Running with dbt=1.8.7', '\x1b[0m04:48:53  Registered adapter: snowflake=1.8.4', '\x1b[0m04:48:53  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m04:48:55  Found 3 models, 454 macros', '\x1b[0m04:48:55', "\x1b[0m04:49:01  Concurrency: 1 threads (target='dev')", '\x1b[0m04:49:01', '\x1b[0m04:49:01  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m04:49:02  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 1.73s]', '\x1b[0m04:49:02', '\x1b[0m04:49:02  Finished running 1 table model in 0 hours 0 minutes and 7.56 seconds (7.56s).', '\x1b[0m04:49:02', '\x1b[0m04:49:02  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m04:49:02', '\x1b[0m04:49:02    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 22 at position 24 unexpected ';'.", '  compiled code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m04:49:02', '\x1b[0m04:49:02  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
[2024-11-20T04:49:04.294+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=publish.customer_metrics_run, execution_date=20241120T044639, start_date=20241120T044850, end_date=20241120T044904
[2024-11-20T04:49:04.305+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 156 for task publish.customer_metrics_run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m04:48:52  Running with dbt=1.8.7', '\x1b[0m04:48:53  Registered adapter: snowflake=1.8.4', '\x1b[0m04:48:53  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m04:48:55  Found 3 models, 454 macros', '\x1b[0m04:48:55', "\x1b[0m04:49:01  Concurrency: 1 threads (target='dev')", '\x1b[0m04:49:01', '\x1b[0m04:49:01  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m04:49:02  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 1.73s]', '\x1b[0m04:49:02', '\x1b[0m04:49:02  Finished running 1 table model in 0 hours 0 minutes and 7.56 seconds (7.56s).', '\x1b[0m04:49:02', '\x1b[0m04:49:02  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m04:49:02', '\x1b[0m04:49:02    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 22 at position 24 unexpected ';'.", '  compiled code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m04:49:02', '\x1b[0m04:49:02  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1'); 18684)
[2024-11-20T04:49:04.341+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-20T04:49:04.354+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
