[2024-11-20T04:17:36.658+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-11-20T04:15:26.082029+00:00 [queued]>
[2024-11-20T04:17:36.671+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-11-20T04:15:26.082029+00:00 [queued]>
[2024-11-20T04:17:36.672+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-20T04:17:36.689+0000] {taskinstance.py:2214} INFO - Executing <Task(DbtRunLocalOperator): publish.customer_metrics_run> on 2024-11-20 04:15:26.082029+00:00
[2024-11-20T04:17:36.694+0000] {standard_task_runner.py:60} INFO - Started process 15911 to run task
[2024-11-20T04:17:36.697+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'publish.customer_metrics_run', 'manual__2024-11-20T04:15:26.082029+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmpdd5scat6']
[2024-11-20T04:17:36.698+0000] {standard_task_runner.py:88} INFO - Job 146: Subtask publish.customer_metrics_run
[2024-11-20T04:17:36.752+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-11-20T04:15:26.082029+00:00 [running]> on host 4cf1ca1acf00
[2024-11-20T04:17:36.850+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='publish.customer_metrics_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T04:15:26.082029+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T04:15:26.082029+00:00'
[2024-11-20T04:17:36.852+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmpvu9_839p from /opt/airflow/include/dbt/fraud
[2024-11-20T04:17:36.855+0000] {config.py:253} INFO - Using user-supplied profiles.yml at /opt/airflow/include/dbt/fraud/profiles.yml
[2024-11-20T04:17:36.856+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
From /tmp/tmpvu9_839p
[2024-11-20T04:17:36.857+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])
[2024-11-20T04:17:36.858+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-11-20T04:17:36.859+0000] {subprocess.py:73} INFO - Running command: ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
[2024-11-20T04:17:36.873+0000] {subprocess.py:84} INFO - Command output:
[2024-11-20T04:17:38.981+0000] {subprocess.py:94} INFO - [0m04:17:38  Running with dbt=1.8.7
[2024-11-20T04:17:40.329+0000] {subprocess.py:94} INFO - [0m04:17:40  Registered adapter: snowflake=1.8.4
[2024-11-20T04:17:40.359+0000] {subprocess.py:94} INFO - [0m04:17:40  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-11-20T04:17:42.227+0000] {subprocess.py:94} INFO - [0m04:17:42  Found 3 models, 454 macros
[2024-11-20T04:17:42.228+0000] {subprocess.py:94} INFO - [0m04:17:42
[2024-11-20T04:17:45.726+0000] {subprocess.py:94} INFO - [0m04:17:45  Concurrency: 1 threads (target='dev')
[2024-11-20T04:17:45.726+0000] {subprocess.py:94} INFO - [0m04:17:45
[2024-11-20T04:17:45.733+0000] {subprocess.py:94} INFO - [0m04:17:45  1 of 1 START sql table model AIRBYTE_SCHEMA.customer_metrics ................... [RUN]
[2024-11-20T04:17:47.471+0000] {subprocess.py:94} INFO - [0m04:17:47  1 of 1 ERROR creating sql table model AIRBYTE_SCHEMA.customer_metrics .......... [[31mERROR[0m in 1.74s]
[2024-11-20T04:17:47.474+0000] {subprocess.py:94} INFO - [0m04:17:47
[2024-11-20T04:17:47.475+0000] {subprocess.py:94} INFO - [0m04:17:47  Finished running 1 table model in 0 hours 0 minutes and 5.25 seconds (5.25s).
[2024-11-20T04:17:47.507+0000] {subprocess.py:94} INFO - [0m04:17:47
[2024-11-20T04:17:47.508+0000] {subprocess.py:94} INFO - [0m04:17:47  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-20T04:17:47.509+0000] {subprocess.py:94} INFO - [0m04:17:47
[2024-11-20T04:17:47.509+0000] {subprocess.py:94} INFO - [0m04:17:47    Database Error in model customer_metrics (models/customer_metrics.sql)
[2024-11-20T04:17:47.510+0000] {subprocess.py:94} INFO -   001003 (42000): SQL compilation error:
[2024-11-20T04:17:47.511+0000] {subprocess.py:94} INFO -   syntax error line 22 at position 24 unexpected ';'.
[2024-11-20T04:17:47.511+0000] {subprocess.py:94} INFO -   compiled code at target/run/fraud/models/customer_metrics.sql
[2024-11-20T04:17:47.512+0000] {subprocess.py:94} INFO - [0m04:17:47
[2024-11-20T04:17:47.513+0000] {subprocess.py:94} INFO - [0m04:17:47  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-11-20T04:17:48.784+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2024-11-20T04:17:48.797+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-11-20T04:17:48.798+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-11-20T04:17:48.803+0000] {local.py:252} INFO - Inlets: []
[2024-11-20T04:17:48.804+0000] {local.py:253} INFO - Outlets: []
[2024-11-20T04:17:48.804+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-11-20T04:17:48.828+0000] {dag.py:3834} INFO - Setting next_dagrun for customer_metrics to 2024-11-20 00:00:00+00:00, run_after=2024-11-21 00:00:00+00:00
[2024-11-20T04:17:48.856+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 257, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 136, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m04:17:38  Running with dbt=1.8.7', '\x1b[0m04:17:40  Registered adapter: snowflake=1.8.4', '\x1b[0m04:17:40  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m04:17:42  Found 3 models, 454 macros', '\x1b[0m04:17:42', "\x1b[0m04:17:45  Concurrency: 1 threads (target='dev')", '\x1b[0m04:17:45', '\x1b[0m04:17:45  1 of 1 START sql table model AIRBYTE_SCHEMA.customer_metrics ................... [RUN]', '\x1b[0m04:17:47  1 of 1 ERROR creating sql table model AIRBYTE_SCHEMA.customer_metrics .......... [\x1b[31mERROR\x1b[0m in 1.74s]', '\x1b[0m04:17:47', '\x1b[0m04:17:47  Finished running 1 table model in 0 hours 0 minutes and 5.25 seconds (5.25s).', '\x1b[0m04:17:47', '\x1b[0m04:17:47  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m04:17:47', '\x1b[0m04:17:47    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 22 at position 24 unexpected ';'.", '  compiled code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m04:17:47', '\x1b[0m04:17:47  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
[2024-11-20T04:17:48.859+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=publish.customer_metrics_run, execution_date=20241120T041526, start_date=20241120T041736, end_date=20241120T041748
[2024-11-20T04:17:48.870+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 146 for task publish.customer_metrics_run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m04:17:38  Running with dbt=1.8.7', '\x1b[0m04:17:40  Registered adapter: snowflake=1.8.4', '\x1b[0m04:17:40  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m04:17:42  Found 3 models, 454 macros', '\x1b[0m04:17:42', "\x1b[0m04:17:45  Concurrency: 1 threads (target='dev')", '\x1b[0m04:17:45', '\x1b[0m04:17:45  1 of 1 START sql table model AIRBYTE_SCHEMA.customer_metrics ................... [RUN]', '\x1b[0m04:17:47  1 of 1 ERROR creating sql table model AIRBYTE_SCHEMA.customer_metrics .......... [\x1b[31mERROR\x1b[0m in 1.74s]', '\x1b[0m04:17:47', '\x1b[0m04:17:47  Finished running 1 table model in 0 hours 0 minutes and 5.25 seconds (5.25s).', '\x1b[0m04:17:47', '\x1b[0m04:17:47  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m04:17:47', '\x1b[0m04:17:47    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 22 at position 24 unexpected ';'.", '  compiled code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m04:17:47', '\x1b[0m04:17:47  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1'); 15911)
[2024-11-20T04:17:48.899+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-20T04:17:48.913+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
