[2024-11-20T03:49:14.000+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-11-20T03:47:11.945088+00:00 [queued]>
[2024-11-20T03:49:14.009+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-11-20T03:47:11.945088+00:00 [queued]>
[2024-11-20T03:49:14.010+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-20T03:49:14.024+0000] {taskinstance.py:2214} INFO - Executing <Task(DbtRunLocalOperator): publish.customer_metrics_run> on 2024-11-20 03:47:11.945088+00:00
[2024-11-20T03:49:14.029+0000] {standard_task_runner.py:60} INFO - Started process 12900 to run task
[2024-11-20T03:49:14.032+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'publish.customer_metrics_run', 'manual__2024-11-20T03:47:11.945088+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmpj0m1cilk']
[2024-11-20T03:49:14.034+0000] {standard_task_runner.py:88} INFO - Job 125: Subtask publish.customer_metrics_run
[2024-11-20T03:49:14.082+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.publish.customer_metrics_run manual__2024-11-20T03:47:11.945088+00:00 [running]> on host 4cf1ca1acf00
[2024-11-20T03:49:14.168+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='publish.customer_metrics_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T03:47:11.945088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T03:47:11.945088+00:00'
[2024-11-20T03:49:14.170+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmpsxybrj5k from /opt/airflow/include/dbt/fraud
[2024-11-20T03:49:14.173+0000] {config.py:253} INFO - Using user-supplied profiles.yml at /opt/airflow/include/dbt/fraud/profiles.yml
[2024-11-20T03:49:14.174+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
From /tmp/tmpsxybrj5k
[2024-11-20T03:49:14.174+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])
[2024-11-20T03:49:14.175+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-11-20T03:49:14.175+0000] {subprocess.py:73} INFO - Running command: ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
[2024-11-20T03:49:14.185+0000] {subprocess.py:84} INFO - Command output:
[2024-11-20T03:49:15.809+0000] {subprocess.py:94} INFO - [0m03:49:15  Running with dbt=1.8.7
[2024-11-20T03:49:16.878+0000] {subprocess.py:94} INFO - [0m03:49:16  Registered adapter: snowflake=1.8.4
[2024-11-20T03:49:16.911+0000] {subprocess.py:94} INFO - [0m03:49:16  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-11-20T03:49:18.517+0000] {subprocess.py:94} INFO - [0m03:49:18  Found 3 models, 454 macros
[2024-11-20T03:49:18.519+0000] {subprocess.py:94} INFO - [0m03:49:18
[2024-11-20T03:49:22.167+0000] {subprocess.py:94} INFO - [0m03:49:22  Concurrency: 1 threads (target='dev')
[2024-11-20T03:49:22.168+0000] {subprocess.py:94} INFO - [0m03:49:22
[2024-11-20T03:49:22.173+0000] {subprocess.py:94} INFO - [0m03:49:22  1 of 1 START sql table model AIRBYTE_SCHEMA.customer_metrics ................... [RUN]
[2024-11-20T03:49:23.982+0000] {subprocess.py:94} INFO - [0m03:49:23  1 of 1 ERROR creating sql table model AIRBYTE_SCHEMA.customer_metrics .......... [[31mERROR[0m in 1.80s]
[2024-11-20T03:49:23.985+0000] {subprocess.py:94} INFO - [0m03:49:23
[2024-11-20T03:49:23.986+0000] {subprocess.py:94} INFO - [0m03:49:23  Finished running 1 table model in 0 hours 0 minutes and 5.47 seconds (5.47s).
[2024-11-20T03:49:24.021+0000] {subprocess.py:94} INFO - [0m03:49:24
[2024-11-20T03:49:24.021+0000] {subprocess.py:94} INFO - [0m03:49:24  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-20T03:49:24.022+0000] {subprocess.py:94} INFO - [0m03:49:24
[2024-11-20T03:49:24.023+0000] {subprocess.py:94} INFO - [0m03:49:24    Database Error in model customer_metrics (models/customer_metrics.sql)
[2024-11-20T03:49:24.023+0000] {subprocess.py:94} INFO -   001003 (42000): SQL compilation error:
[2024-11-20T03:49:24.024+0000] {subprocess.py:94} INFO -   syntax error line 22 at position 24 unexpected ';'.
[2024-11-20T03:49:24.025+0000] {subprocess.py:94} INFO -   compiled code at target/run/fraud/models/customer_metrics.sql
[2024-11-20T03:49:24.025+0000] {subprocess.py:94} INFO - [0m03:49:24
[2024-11-20T03:49:24.026+0000] {subprocess.py:94} INFO - [0m03:49:24  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-11-20T03:49:25.269+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2024-11-20T03:49:25.283+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-11-20T03:49:25.284+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-11-20T03:49:25.291+0000] {local.py:252} INFO - Inlets: []
[2024-11-20T03:49:25.292+0000] {local.py:253} INFO - Outlets: []
[2024-11-20T03:49:25.293+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-11-20T03:49:25.318+0000] {dag.py:3834} INFO - Setting next_dagrun for customer_metrics to 2024-11-20 00:00:00+00:00, run_after=2024-11-21 00:00:00+00:00
[2024-11-20T03:49:25.348+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 257, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 136, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m03:49:15  Running with dbt=1.8.7', '\x1b[0m03:49:16  Registered adapter: snowflake=1.8.4', '\x1b[0m03:49:16  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m03:49:18  Found 3 models, 454 macros', '\x1b[0m03:49:18', "\x1b[0m03:49:22  Concurrency: 1 threads (target='dev')", '\x1b[0m03:49:22', '\x1b[0m03:49:22  1 of 1 START sql table model AIRBYTE_SCHEMA.customer_metrics ................... [RUN]', '\x1b[0m03:49:23  1 of 1 ERROR creating sql table model AIRBYTE_SCHEMA.customer_metrics .......... [\x1b[31mERROR\x1b[0m in 1.80s]', '\x1b[0m03:49:23', '\x1b[0m03:49:23  Finished running 1 table model in 0 hours 0 minutes and 5.47 seconds (5.47s).', '\x1b[0m03:49:24', '\x1b[0m03:49:24  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m03:49:24', '\x1b[0m03:49:24    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 22 at position 24 unexpected ';'.", '  compiled code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m03:49:24', '\x1b[0m03:49:24  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
[2024-11-20T03:49:25.352+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=publish.customer_metrics_run, execution_date=20241120T034711, start_date=20241120T034914, end_date=20241120T034925
[2024-11-20T03:49:25.364+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 125 for task publish.customer_metrics_run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m03:49:15  Running with dbt=1.8.7', '\x1b[0m03:49:16  Registered adapter: snowflake=1.8.4', '\x1b[0m03:49:16  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m03:49:18  Found 3 models, 454 macros', '\x1b[0m03:49:18', "\x1b[0m03:49:22  Concurrency: 1 threads (target='dev')", '\x1b[0m03:49:22', '\x1b[0m03:49:22  1 of 1 START sql table model AIRBYTE_SCHEMA.customer_metrics ................... [RUN]', '\x1b[0m03:49:23  1 of 1 ERROR creating sql table model AIRBYTE_SCHEMA.customer_metrics .......... [\x1b[31mERROR\x1b[0m in 1.80s]', '\x1b[0m03:49:23', '\x1b[0m03:49:23  Finished running 1 table model in 0 hours 0 minutes and 5.47 seconds (5.47s).', '\x1b[0m03:49:24', '\x1b[0m03:49:24  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m03:49:24', '\x1b[0m03:49:24    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 22 at position 24 unexpected ';'.", '  compiled code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m03:49:24', '\x1b[0m03:49:24  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1'); 12900)
[2024-11-20T03:49:25.389+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-20T03:49:25.403+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
